config/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from core.admin import admin_site
from core.views import admin_login_view

urlpatterns = [
    path("admin/login/", admin_login_view, name="admin-login-override"),
    path("admin/", admin_site.urls),
    path("auth/", include("authbroker_client.urls", namespace="authbroker_client")),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("2fa/", include("twofactor.urls", namespace="twofactor")),
    path("user/", include("user.urls", namespace="user")),
    path("", include("secret.urls", namespace="secret")),
    path("", include(("localauth.urls", "localauth"), namespace="localauth")),
]

secret/urls.py
from django.urls import path

from . import views

app_name = "secret"

urlpatterns = [
    path("", views.SecretListView.as_view(), name="list"),
    path("create/", views.SecretCreateView.as_view(), name="create"),
    path("secret/<str:pk>/", views.SecretDetailView.as_view(), name="detail"),
    path("secret/<str:pk>/delete/", views.SecretDeleteView.as_view(), name="delete"),
    path(
        "secret/<str:pk>/mfa/setup/",
        views.SecretMFASetupView.as_view(),
        name="mfa_setup",
    ),
    path(
        "secret/<str:pk>/mfa/delete/",
        views.SecretMFADeleteView.as_view(),
        name="mfa_delete",
    ),
    path(
        "secret/<str:pk>/mfa/",
        views.SecretMFAView.as_view(),
        name="mfa",
    ),
    path("secret/<str:pk>/audit/", views.SecretAuditView.as_view(), name="audit"),
    path(
        "secret/<str:pk>/sharing/",
        views.SecretPermissionsView.as_view(),
        name="permissions",
    ),
    path(
        "secret/<str:pk>/sharing/delete/",
        views.SecretPermissionsDeleteView.as_view(),
        name="delete-permission",
    ),
    path("secret/<str:pk>/files/", views.SecretFileListView.as_view(), name="file_list"),
    path("secret/<str:pk>/files/add/", views.SecretFileUploadView.as_view(), name="file_add"),
    path("secret/<str:pk>/files/delete/<str:file_pk>/", views.SecretFileDeleteView.as_view(), name="file_delete"),
    path("secret/<str:pk>/files/download/<str:file_pk>/", views.SecretFileDownloadView.as_view(), name="file_download"),
]

user/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "user"

urlpatterns = [
    path(
        "disabled",
        TemplateView.as_view(template_name="user/account-disabled.html"),
        name="disabled",
    ),
    path(
        "logged-out", TemplateView.as_view(template_name="user/logged-out.html"), name="logged-out",
    ),
]

audit/models.py
import datetime as dt
from django.db import models

from django.utils import timezone
from django.conf import settings

from .types import StrEnum


class Actions(StrEnum):
    imported = "Imported"
    create_secret = "Created"
    update_secret = "Updated"
    delete_secret = "Deleted"
    view_secret = "Viewed"
    add_permission = "Added permission"
    remove_permission = "Removed permission"
    setup_mfa = "Set up MFA client"
    delete_mfa = "Delete MFA client"
    generate_mfa_token = "Generate MFA token"
    download_file = "Download file"
    upload_file = "Upload file"
    delete_file = "Delete file"


class Audit(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey("user.User", on_delete=models.PROTECT)
    secret = models.ForeignKey("secret.Secret", on_delete=models.PROTECT, null=True, blank=True)
    action = models.CharField(choices=Actions.list(), max_length=255)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name_plural = "audit"


def create_audit_event(user, action: Actions, description=None, secret=None, report_once=False):
    """
    Create an audit event

    If `report_once` is True, then the event will not be created if an event with the same user & action exists
    within the `settings.AUDIT_EVENT_REPEAT_AFTER_MINUTES` period.
    """
    if report_once:
        report_window_start = timezone.now() - dt.timedelta(
            minutes=settings.AUDIT_EVENT_REPEAT_AFTER_MINUTES
        )

        query = {"user": user, "action": action.name, "timestamp__gte": report_window_start}

        if secret:
            query["secret"] = secret

        if Audit.objects.filter(**query).exists():
            return

    Audit.objects.create(
        user=user,
        action=action.name,
        description=description or "",
        secret=secret,
    )

secret/models.py
import uuid

from django.db import models
from django.urls import reverse

from django_cryptography.fields import encrypt
from guardian.models import UserObjectPermissionBase
from guardian.models import GroupObjectPermissionBase
from guardian.shortcuts import (
    assign_perm,
    get_user_perms,
    get_group_perms,
    remove_perm,
)

import pyotp

from user.models import User


class Secret(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    created_by = models.ForeignKey("user.User", on_delete=models.SET_NULL, null=True)

    deleted = models.BooleanField(default=False)

    name = models.CharField(max_length=255)

    url = models.URLField(blank=True)
    username = models.CharField(max_length=255, blank=True)
    password = encrypt(models.CharField(max_length=255, blank=True))
    details = encrypt(models.TextField(blank=True))

    mfa_string = encrypt(models.CharField(max_length=255, blank=True))

    @property
    def mfa_code(self):
        if hasattr(self, "mfaclient"):
            return self.mfaclient.generate_code() if self.mfaclient else None

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("secret:detail", args=[self.id])

    def _get_perms(self, target):
        if isinstance(target, User):
            return get_user_perms(target, self)
        else:
            return get_group_perms(target, self)

    def set_permission(self, target, permission):
        current_perms = set(self._get_perms(target))

        required_perms = (
            {"view_secret", "change_secret"} if permission == "change_secret" else {"view_secret"}
        )

        for permission in list(required_perms.difference(current_perms)):
            assign_perm(permission, target, self)

        for permission in list(current_perms.difference(required_perms)):
            remove_perm(permission, target, self)

    def remove_permissions(self, target):
        permissions = self._get_perms(target)

        for perm in permissions:
            remove_perm(perm, target, self)

    def get_otp(self):
        if not self.mfa_string:
            return None

        otp = pyotp.parse_uri(self.mfa_string)

        # the library fails to cast the interval field to a number,
        # despite requiring that the field be a number
        otp.interval = int(otp.interval)

        return otp

    def verify_otp(self, code):
        return self.get_otp().verify(code)

    def generate_otp_code(self):
        otp = self.get_otp()

        return None if not otp else otp.now()


class SecretFile(models.Model):
    secret = models.ForeignKey(Secret, related_name="files", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    file_name = models.CharField(max_length=255)
    file_data = encrypt(models.BinaryField(null=True))


class SecretUserObjectPermission(UserObjectPermissionBase):
    content_object = models.ForeignKey(Secret, on_delete=models.CASCADE)


class SecretGroupObjectPermission(GroupObjectPermissionBase):
    content_object = models.ForeignKey(Secret, on_delete=models.CASCADE)

secret/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model

from PIL import Image
import pyotp
from pyzbar import pyzbar

from crispy_forms.bootstrap import PrependedAppendedText, AppendedText, FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Field, Layout, Row, Submit

from .models import Secret


EDIT_SECRET_PERMISSION = "change_secret"
VIEW_SECRET_PERMISSION = "view_secret"

PERMISSION_CHOICES = (
    (VIEW_SECRET_PERMISSION, "View"),
    (EDIT_SECRET_PERMISSION, "Change"),
)


def clipboard_html(input_id):
    return mark_safe(f'<span copy="{input_id}" class="fa fa-clipboard copy-to-clipboard"></span>')


def showpassword_html(input_id):
    return mark_safe(
        f'<span toggle="{input_id}" class="fa fa-fw fa-eye-slash field-icon toggle-password"></span>'
    )


class SecretUpdateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(render_value=True), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column("name"),
                Column(AppendedText("url", clipboard_html("#id_url"))),
                css_class="form-row",
            ),
            Row(
                Column(
                    AppendedText("username", clipboard_html("#id_username")), autocomplete="off"
                ),
                Column(
                    PrependedAppendedText(
                        "password",
                        showpassword_html("#id_password"),
                        clipboard_html("#id_password"),
                        autocomplete="off",
                    ),
                ),
                css_class="form-row",
            ),
            Field("details", autocomplete="off"),
            FormActions(
                Submit("save", "Update secret"),
            ),
        )

    class Meta:
        model = Secret
        fields = [
            "name",
            "url",
            "username",
            "password",
            "details",
        ]


class SecretCreateForm(SecretUpdateForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper.layout[-1] = FormActions(
            Submit("save", "Create secret"),
        )


class SecretPermissionsForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=get_user_model().objects.all().exclude(email="AnonymousUser"),
        required=False,
        widget=forms.HiddenInput(),
    )
    group = forms.ModelChoiceField(
        queryset=Group.objects.all().order_by("name"),
        required=False,
        widget=forms.HiddenInput(),
    )
    permission = forms.ChoiceField(
        choices=PERMISSION_CHOICES,
        widget=forms.HiddenInput(),
    )

    def __init__(self, *args, update_permission=False, **kwargs):
        super().__init__(*args, **kwargs)

        if update_permission:
            self.fields["permission"].widget = forms.Select()
            self.fields["permission"].choices = PERMISSION_CHOICES

            self.helper = FormHelper()
            self.helper.form_class = "update_perms"
            self.helper.form_show_labels = False
            self.helper.layout = Layout(
                "user",
                "group",
                Field("permission", css_class="form-control-sm"),
            )

    def clean(self):
        cleaned_data = super().clean()

        if not cleaned_data["user"] and not cleaned_data["group"]:
            raise forms.ValidationError("Select either a user or a group")

        return cleaned_data


class SecretGroupPermissionsForm(forms.Form):
    group = forms.ModelChoiceField(queryset=Group.objects.all().order_by("name"))
    permission = forms.ChoiceField(choices=PERMISSION_CHOICES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column("group"), Column("permission"), css_class="form-row"),
            FormActions(
                Submit("add", "Add"),
            ),
        )


class SecretUserPermissionsForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=get_user_model().objects.all().exclude(email="AnonymousUser")
    )
    permission = forms.ChoiceField(choices=PERMISSION_CHOICES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column("user"), Column("permission"), css_class="form-row"),
            FormActions(
                Submit("add", "Add"),
            ),
        )


class MFAClientSetupForm(forms.Form):
    qr_code = forms.ImageField(
        label="QR Code",
        required=False,
        help_text="Screen shot and upload an image of the MFA QR code",
    )
    mfa_string = forms.CharField(
        label="MFA String",
        max_length=255,
        required=False,
        help_text="Or, manually enter the MFA string",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field("qr_code"),
            Field("mfa_string"),
            FormActions(
                Submit("Enable", "Enable"),
            ),
        )

    def clean(self):
        cleaned_data = super().clean()

        if not cleaned_data["qr_code"] and not cleaned_data["mfa_string"]:
            raise forms.ValidationError(
                "Either upload an screenshot of an QR code OR enter "
                "the MFA code string manually; only one field is required."
            )

        if cleaned_data["qr_code"]:
            decoded = self.extract_code_from_qr_image(cleaned_data["qr_code"])

            if not decoded:
                raise form.ValidationError("Invalid QR code")

            if self.is_valid_otp_string(decoded):
                cleaned_data["mfa_string"] = decoded
                return cleaned_data

        if cleaned_data["mfa_string"]:
            if self.is_valid_otp_string(cleaned_data["mfa_string"]):
                return cleaned_data

        raise forms.ValidationError("Unable to validate QR code")

    def is_valid_otp_string(self, mfa_string):
        try:
            pyotp.parse_uri(mfa_string)
            return True
        except ValueError:
            return False

    def extract_code_from_qr_image(self, image_field):
        image = Image.open(image_field)
        decoded = pyzbar.decode(image)

        if len(decoded):
            if decoded[0].type == "QRCODE":
                return decoded[0].data.decode("utf-8")

        return None


class SecretFileUploadForm(forms.Form):
    file = forms.FileField(
        label="file",
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field("file"),
            FormActions(
                Submit("Upload", "Upload"),
            ),
        )

    def clean(self):
        cleaned_data = super().clean()

        return cleaned_data

templates/secret/confirm-delete.html
{% extends "base.html" %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<h4 class="pt-3">Confirm remove access</h4>

<p class="pt-3">
    Confirm remove access to secret <strong>"{{ object.name }}"</strong> for {{ object_type }} <strong>{{ target }}</strong>?
</p>

<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    <input type="hidden" name="{{ object_type }}" value="{{ target.id }}">
    <button type="submit" class="btn btn-danger">Remove access</button>
</form>

{% endblock %}}

templates/secret/file_delete.html
{% extends "base.html" %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<h4 class="pt-3">Confirm delete file</h4>

<p class="pt-3">
    Delete file <strong>{{ file.file_name }}</strong>?
</p>

<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    <input type="hidden" name="{{ object_type }}" value="{{ target.id }}">
    <button type="submit" class="btn btn-danger">Delete file</button>
</form>

{% endblock %}}

templates/secret/file_list.html
{% extends "base.html" %}

{% load guardian_tags %}

{% block main %}

{% include "partials/secret-nav.html" %}

{% get_obj_perms request.user for object as "secret_perms" %}

  <div class="row mt-4">
    <div class="col-sm">

      <table class="table">
        <tbody>
          {% for file in object.files.all %}
          <tr>
            <th scope="row">{{ file.file_name }}</th>
            <td>{{ file.created }}</td>
            <td><a href="{% url 'secret:file_download' pk=pk file_pk=file.pk %}">Download</a></td>
            <td>
              {% if "change_secret" in secret_perms %}
              <a href="{% url 'secret:file_delete' pk=pk file_pk=file.pk %}">Delete</a>
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <tr>
            <td>No files available</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if "change_secret" in secret_perms %}
      <a class="btn btn-danger" href="{% url 'secret:file_add' pk=pk %}" role="button">Upload a file</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/secret/file_upload.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block main %}

{% include "partials/secret-nav.html" %}

  <div class="row mt-4">
    <div class="col-sm">


        {% crispy form %}

      {% if "change_secret" in secret_perms %}
      <a class="btn btn-danger" href="{% url 'secret:file_add' pk=pk %}" role="button">Upload a file</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/secret/mfa.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block main %}

{% include "partials/secret-nav.html" %}

  <div class="row mt-4">
    <div class="col-sm">

      {% if object.mfa_string %}
      <div class="jumbotron">
        <h1 class="display-4">{{ object.generate_otp_code }}</h1>
      </div>

      <a class="btn btn-danger" href="{% url 'secret:mfa_delete' pk=pk %}" role="button">Delete MFA client</a>
      {% else %}
      <a class="btn btn-danger" href="{% url 'secret:mfa_setup' pk=pk %}" role="button">Setup MFA client</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">

    {{ block.super }}
    {% if mfa_code %}
    setTimeout(function(){
        location.reload();
    },2000);
    {% endif %}
</script>
{% endblock %}

templates/secret/mfa_delete.html
{% extends "base.html" %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<h4 class="pt-3">Confirm remove MFA client</h4>

<p class="pt-3">
    Confirm remove MFA client for <strong>"{{ object.name }}"</strong> for {{ object_type }} <strong></strong>?
</p>

<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Remove MFA client</button>
</form>

{% endblock %}}

templates/secret/mfa_setup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block main %}

{% include "partials/secret-nav.html" %}

{% crispy form %}

{% endblock %}}

templates/secret/permissions.html
{% extends "base.html" %}

{% load crispy_forms_tags static %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">User/Group</th>
      <th scope="col">Permission</th>
      <th scope="col" class="text-right">Remove</th>
    </tr>
  </thead>
  <tbody>
    {% for row in groups %}
    <tr>
      <td>{{ row.group }}</td>
      <td>
          {% crispy row.form %}
      </td>
      <td class="text-right">
          <a href="{% url 'secret:delete-permission' pk=pk %}?group={{ row.group.id }}" class="badge badge-danger">Delete</a>
      </td>
    </tr>
    {% endfor %}
    {% for row in users %}
    <tr>
      <td>{{ row.user }}</td>
      <td>
          {% crispy row.form %}
      </td>
      <td class="text-right">
          <a href="{% url 'secret:delete-permission' pk=pk %}?user={{ row.user.id }}" class="badge badge-danger">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h5>Add a group</h5>
{% crispy group_form %}

<h5>Add a user</h5>
{% crispy user_form %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link href="{% static "css/select2-bootstrap4.min.css" %}" rel="stylesheet" />
{% endblock %}

{% endblock %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script type="text/javascript">
{{ block.super }}
$(document).ready(function() {
    $('#id_group,#id_user').select2({
        theme: 'bootstrap4'
    });

    $('form.update_perms select').change(function(){
        $(this).parents("form.update_perms").submit();
    });
});
</script>
{% endblock %}

templates/secret/secret_audit.html
{% extends "base.html" %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Action</th>
                    <th scope="col">User</th>
                    <th scope="col">Details</th>
                </tr>
                </thead>
                <tbody>
                {% for audit in audit_info %}
                <tr>
                    <th scope="row">{{ audit.timestamp }}</th>
                    <td>{{ audit.get_action_display }}</td>
                    <td>{{ audit.user }}</td>
                    <td>{{ audit.description }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}}

templates/secret/secret_confirm_delete.html
{% extends "base.html" %}

{% block main %}

{% include 'partials/secret-nav.html' %}

<h4 class="pt-3">Confirm delete secret</h4>

<p class="pt-3">
    Are you sure you want to delete {{ object }}?
</p>

<form method="post" action="{{ request.path }}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock %}}

templates/secret/secret_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block main %}

{% include 'partials/secret-nav.html' %}

   {% if secret.mfa_string %}
   <div class="my-2">
     <form method="post" action="{% url 'secret:mfa' pk=pk %}">
        <button type="submit" class="btn btn-secondary">Generate MFA token</button>
     </form>
   </div>
   {% endif %}

   {% crispy form %}

{% endblock %}}

{% block javascript %}
<script type="text/javascript">
    {{ block.super }}
    $(document).ready(function(){
        $(".toggle-password").click(function() {
            $(this).toggleClass("fa-eye fa-eye-slash");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
                input.attr("type", "text");
            }
            else{
                input.attr("type", "password");
            }
        });
        $(".copy-to-clipboard").click(function() {
            var input = $($(this).attr("copy"));
            var isPassword = input.attr("type") == "password"

            if(isPassword) {
                input.attr("type", "text");
            }

            input.select();
            document.execCommand("copy");

            if(isPassword) {
                input.attr("type", "password");
            }
        });
    });
</script>
{% endblock %}

templates/secret/secret_list.html
{% extends "base.html" %}

{% load filter_tags %}

{% block main %}

<h1>Passwords</h1>

    <table class="table table-striped" id="secrets-list">
        <thead>
        <tr>
            <th scope="col"><a href="{{ request.path }}{% filter_querystring 'name' %}" class="text-dark text-nowrap">Name <i class="fa fa-sort" aria-hidden="true"></i></a></th>
            <th scope="col"><a href="{{ request.path }}{% filter_querystring 'username' %}" class="text-dark text-nowrap">Username <i class="fa fa-sort" aria-hidden="true"></i></a></th>
            <th scope="col"><a href="{{ request.path }}{% filter_querystring 'url' %}" class="text-dark text-nowrap">Url <i class="fa fa-sort" aria-hidden="true"></i></a></th>
            <th scope="col"><a href="{{ request.path }}{% filter_querystring 'last_updated' %}" class="text-dark text-nowrap">Last updated <i class="fa fa-sort" aria-hidden="true"></i></a></th>
        </tr>
        </thead>
        <tbody>
        {% for secret in page_obj %}
        <tr>
            <td><a href="{{ secret.get_absolute_url }}" title="{{ secret.name }}">{{ secret.name|truncatechars:50 }}</a></td>
            <td>{{ secret.username|truncatechars:30 }}</td>
            <td>{% if secret.url %}<a href="{{ secret.url }}" _blank="True" title="{{ secret.url }}">{{ secret.url|truncatechars:50 }}</a>{% endif %}</td>
            <td>{{ secret.last_updated }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No passwords available.</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
          <a class="page-link" href="{% if page_obj.has_previous %}{% page_querystring page_obj.previous_page_number %}{% endif %}" tabindex="-1">Previous</a>
        </li>
        {% for page_index in paginator.page_range %}
        <li class="page-item {% if page_index == page_obj.number %}disabled{% endif %}">
            <a class="page-link" href="{% page_querystring page_index %}">{{ page_index }}</a>
        </li>
        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
          <a class="page-link" href="{% if page_obj.has_next %}{% page_querystring page_obj.next_page_number %}{% endif %}">Next</a>
        </li>
      </ul>
    </nav>

    <a href="{% url 'secret:create' %}" class="btn btn-primary">
        Add new secret
    </a>

{% endblock %}