config/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from core.admin import admin_site
from core.views import admin_login_view

urlpatterns = [
    path("admin/login/", admin_login_view, name="admin-login-override"),
    path("admin/", admin_site.urls),
    path("auth/", include("authbroker_client.urls", namespace="authbroker_client")),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("2fa/", include("twofactor.urls", namespace="twofactor")),
    path("user/", include("user.urls", namespace="user")),
    path("", include("secret.urls", namespace="secret")),
    path("", include(("localauth.urls", "localauth"), namespace="localauth")),
]

secret/urls.py
from django.urls import path

from . import views

app_name = "secret"

urlpatterns = [
    path("", views.SecretListView.as_view(), name="list"),
    path("create/", views.SecretCreateView.as_view(), name="create"),
    path("secret/<str:pk>/", views.SecretDetailView.as_view(), name="detail"),
    path("secret/<str:pk>/delete/", views.SecretDeleteView.as_view(), name="delete"),
    path(
        "secret/<str:pk>/mfa/setup/",
        views.SecretMFASetupView.as_view(),
        name="mfa_setup",
    ),
    path(
        "secret/<str:pk>/mfa/delete/",
        views.SecretMFADeleteView.as_view(),
        name="mfa_delete",
    ),
    path(
        "secret/<str:pk>/mfa/",
        views.SecretMFAView.as_view(),
        name="mfa",
    ),
    path("secret/<str:pk>/audit/", views.SecretAuditView.as_view(), name="audit"),
    path(
        "secret/<str:pk>/sharing/",
        views.SecretPermissionsView.as_view(),
        name="permissions",
    ),
    path(
        "secret/<str:pk>/sharing/delete/",
        views.SecretPermissionsDeleteView.as_view(),
        name="delete-permission",
    ),
    path("secret/<str:pk>/files/", views.SecretFileListView.as_view(), name="file_list"),
    path("secret/<str:pk>/files/add/", views.SecretFileUploadView.as_view(), name="file_add"),
    path("secret/<str:pk>/files/delete/<str:file_pk>/", views.SecretFileDeleteView.as_view(), name="file_delete"),
    path("secret/<str:pk>/files/download/<str:file_pk>/", views.SecretFileDownloadView.as_view(), name="file_download"),
]

user/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "user"

urlpatterns = [
    path(
        "disabled",
        TemplateView.as_view(template_name="user/account-disabled.html"),
        name="disabled",
    ),
    path(
        "logged-out", TemplateView.as_view(template_name="user/logged-out.html"), name="logged-out",
    ),
]

templates/partials/messages.html
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
  </div>
  {% endfor %}
{% endif %}

templates/partials/secret-audit.html
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h4>Audit</h4>
            <table class="table table-sm">
                <thead>
                <tr>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Action</th>
                    <th scope="col">User</th>
                    <th scope="col">Details</th>
                </tr>
                </thead>
                <tbody>
                {% for audit in audit_info %}
                <tr>
                    <th scope="row">{{ audit.timestamp }}</th>
                    <td>{{ audit.action }}</td>
                    <td>{{ audit.user }}</td>
                    <td>{{ audit.details }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

templates/partials/secret-nav.html
{% load guardian_tags %}

{% if not pk %}

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="">Create</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="">Sharing available after save</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="">MFA client available after save</a>
  </li>
</ul>

{% else %}

<h2>{{ object.name }}</h2>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link{% if tab == "view" %} active{% endif %}" href="{% url 'secret:detail' pk=pk %}">View</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if tab == "mfa" %} active{% endif %}" href="{% url 'secret:mfa' pk=pk %}">MFA client</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if tab == "files" %} active{% endif %}" href="{% url 'secret:file_list' pk=pk %}">Files</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if tab == "permissions" %} active{% endif %}" href="{% url 'secret:permissions' pk=pk %}">Sharing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if tab == "audit" %} active{% endif %}" href="{% url 'secret:audit' pk=pk %}">Audit</a>
  </li>
  {% get_obj_perms request.user for object as "secret_perms" %}

  {% if "change_secret" in secret_perms %}
  <li class="nav-item">
    <a class="nav-link{% if tab == "delete" %} active{% endif %}" href="{%  url 'secret:delete' pk=pk %}">Delete</a>
  </li>
  {% endif %}
</ul>

{% endif %}

templates/partials/side-nav.html
<ul class="nav flex-column mb-2">
    <li class="nav-item">
      <a class="nav-link {% if not filter_group and not search_term and page_obj %} disabled{% endif %}" href="{% url 'secret:list' %}">Show all</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if filter_group == "__me" %} disabled{% endif %}" href="{% url 'secret:list' %}?me=True">My passwords</a>
    </li>
</ul>

<h6>Groups</h6>

<ul class="nav flex-column">
    {% for group in request.user.get_permitted_groups %}
    <li class="nav-item" >
      <a class="nav-link {% if filter_group == group.name %} disabled{% endif %}" href="{% url 'secret:list' %}?group={{ group.name }}">{{ group.name }}</a>
    </li>
    {% empty %}
    <li class="nav-item">You do not belong to any groups.</li>
    {% endfor %}
</ul>

templates/partials/top-nav.html
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <a class="navbar-brand" href="/">Password Manager (rattic 2.0)</a>

      {% if request.user.is_authenticated %}

          <ul class="navbar-nav ml-auto">
            <li class="nav-item px-2">
          <form method="get" action="{% url 'secret:list' %}" class="form-inline">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search" id="search" name="name" {% if search_term %}value="{{ search_term }}"{% endif %}>
            <button type="submit" class="btn btn-primary" name="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
            </li>
          {% if request.user.is_superuser or request.user.is_staff %}
            <li class="nav-item px-2">
              <a href="{% url 'admin:index' %}" class="btn btn-danger">Admin section</a>
            </li>
          {% endif %}
            <li class="nav-item px-2">
          <a href="/logout/" class="btn {% if request.user.is_verified %}btn-warning{% else %}btn-secondary{% endif %}">{{ request.user.get_full_name }}, logout</a>
          </li>
          </ul>

      {% endif %}

    </nav>